### ISSUE TITLE
Vanity page Interests have HTML characters. Also change footer to contact DMCC, maybe?

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#299] opened 2023-11-07 23:49 UTC
## 🐛 Describe the Bug
These are really small things, that can be low priority.
The Investigator page has the funky HTML characters showing up in the Interests section.
https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/193-boston-university/roy-hemant-k/

Also, should we change the contact the Informatics Center to Contact the DMCC? They need to change this at DMCC, right?
<img width="950" alt="Screenshot 2023-11-07 at 11 40 18 AM" src="https://github.com/EDRN/P5/assets/58526347/937eb0e1-47b5-44cf-9655-77e2a3463c6c">

**Comment by nutjob4life** [comment] 2023-11-08 02:41
The HTML entities `&quot;` are almost certainly bad data from the DMCC. But we can—like we do for _a lot_ of their data—mask it. Let me know if that's preferable to asking them to fix it on their end.

And yes, we can change the link to DMCC. Should it be an email address? `edrndmcc@fredhutch.org`, right?

**Comment by nutjob4life** [comment] 2023-11-08 14:55
Confirmed my examining the raw data over the SOAP XML API:

<img width="598" alt="Screenshot 2023-11-08 at 8 29 50 AM" src="https://github.com/EDRN/P5/assets/814813/89291b25-1595-41aa-b2ff-7d097aa1c7f4">

After conversion from XML to text, the

    &amp;quot;field effect&amp;quot;

becomes

    &quot;field effect&quot;

which is what's stored in the portal database.

Now if we're supposed to treat interest descriptions as HTML, then storing that in the database is fine.

I looked closer at the interest descriptions from the DMCC and I see a mix of HTML and plain text. For example:

### Person 1664

This person has an interest that contains `James Lyons-Weiler, Ph.D. is an Assistant Professor in the Department of Biomedical Informatics & Interdisciplinary…` which contains an ampersand `&` which _looks like plain text_.

If it were HTML, it should've been `…Informatics &amp; Interdisciplinary…`

### Person 1168

This person has an interest that contains `…peptide peaks may constitute &quot;malignant&quot; protein profiles…` which _looks like HTML_.

If it were plain text, it should've been `peptide peaks may constitute "malignant" protein profiles…`


### Person 1911

This person has an interest that contains `…we have evaluated >110 biomarkers…` which _looks like plain text_.

If it were HTML, it should've been `…we have evaluated &gt;110 biomarkers…`


### Person 1726

This person has an interest that contains
```
…20 graduate students and 40 research fellows. <br><br>The landmark study thus far from Dr. Chinnaiyan’s…
```
which, thanks to the `<br><br>`, _absolutely looks like HTML_.

But if it were plain text, it should've been
```
…20 graduate students and 40 research fellows. 

The landmark study thus far from Dr. Chinnaiyan’s…
```

So two issues:

1. How should research descriptions be interpreted? As plain text or as HTML?
2. Regardless of how the DMCC answers that, they'll need to fix their data, as there are errors in both cases.


### Short Term

For now, I'll have the portal mask these specific circumstances. 

And I'll use `edrndmcc@fredhutch.org` as the contact email.

**Comment by nutjob4life** [comment] 2023-11-08 16:01
@hoodriverheather the workaround is now in place; see https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/193-boston-university/roy-hemant-k/ for an example.

(Some day, our code will be more workarounds than function! 😝)

**Comment by hoodriverheather** [comment] 2023-11-08 21:35
@nutjob4life This looks great!
We should ask them to fix. Do you want to draft an email?

**Comment by nutjob4life** [comment] 2023-11-08 23:19
@hoodriverheather here you go:

### Draft

Greetings DMCC:

The new Interest Descriptions in the SOAP API seem to have a mix of either plain text or HTML formatting, and we're not sure which we should use when displaying Interest Descriptions in the portal.

For example, person 1664 has an Interest Description that in the SOAP API that contains `…James Lyons-Weiler, Ph.D. is an Assistant Professor in the Department of Biomedical Informatics & Interdisciplinary…` which contains a bare ampersand `&` which looks like plain text.

But if it were HTML, it should've been `…Informatics &amp; Interdisciplinary…`, with the ampersand encoded as `&amp;` in the SOAP API.

Person 1168, has an Interest Description that contains `…peptide peaks may constitute &quot;malignant&quot; protein profiles…` which looks like HTML in the SOAP API.

But if it were plain text, it should've been `peptide peaks may constitute "malignant" protein profiles…`, with `"` marks in the SOAP API.

Person 1911 has an Interest Description that contains `…we have evaluated >110 biomarkers…` which looks like plain text in the SOAP API.

If it were HTML, it should've been `…we have evaluated &gt;110 biomarkers…`, with the `>` encoded as `&gt;` in the API.

As a final example, person 1726 has an interest that contains
```
…20 graduate students and 40 research fellows. <br><br>The landmark study thus far from Dr. Chinnaiyan’s…
```
which, thanks to the `<br><br>`, absolutely looks like HTML coming across the SOAP API.

But if it were plain text, it should've been
```
…20 graduate students and 40 research fellows. 

The landmark study thus far from Dr. Chinnaiyan’s…
```
in the SAOP API instead.

So we're not sure if we should treat these Interest Descriptions as plain text or as HTML.

- If they're truly plain text, then the upstream data in the SOAP API should replace HTML markup like `<br>` and HTML entities like `&quot;` with their plain text counterparts.
- But if they're supposed to be HTML, then the upstream data in the SOAP API should replace unencoded `&` and `<` with their entity representations.

We appreciate your help in figuring this out.

**Comment by nutjob4life** [comment] 2023-11-10 13:49
@hoodriverheather I see a QC label on this issue so I'm closing it to help stay on top of what needs to be done and what's been accomplished for 6.7. Do feel free to re-open it, though, for any reason.

**Closed by nutjob4life** 2023-11-10 13:49 UTC
Labels: 🐛bug, ✅ QC
