### ISSUE TITLE
Add Public Outcome to Protocol page on public portal

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#349] opened 2024-03-14 16:32 UTC
@nutjob4life There should be a Public Outcomes and Private Outcomes field in SOAP API from DMCC. Please add the Public Outcomes field to the Protocol page on the Public Portal.

**Comment by nutjob4life** [comment] 2024-03-14 16:34
Duplicate of #348

**Closed** 2024-04-08 19:26 UTC
Labels: 🧙‍♀️enhancement, 🚫won't fix
